---
- name: install node and npm
  hosts: ec2-instance
  become: true
  tasks:
     - name: update apt repo
       apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
     - name: install nodejs and npm
       apt: 
         pkg:
           - nodejs
           - npm

      
- name: deploy nodejs app
  hosts: ec2-instance
  tasks:
     - name: Copy nodejs folder to a server
       copy:
          src: /Users/mac/Containerized-nodejs/nodejs-app-1.0.0.tgz
          dest: /home/ubuntu/app-1.2.0.tgz

     - name: unpack the nodejs tar file
       unarchive: 
          src: /home/ubuntu/app-1.2.0.tgz
          dest: /home/ubuntu/
          remote_src: yes

     - name: install all dependencies
       npm:
         path: /home/ubuntu/package

     - name: start application
       command: node /home/ubuntu/package/app/server.js
       async: 1000
       poll: 0

     - name: ensure that the app is running
       shell: ps aux | grep node  #checking if app is running
       register: status_of_app
     - debug: msg={{status_of_app.stdout_lines}}

